# Whether or not to enable invisible item frames glowing when there's no item in them
# This will also make them visible when there's no item in them
item-frames-glow: true

# The items which can be in the center of the recipe
recipes:
  -
    ==: org.bukkit.inventory.ItemStack
    v: 2567
    type: LINGERING_POTION
    meta:
      ==: ItemMeta
      meta-type: POTION
      potion-type: minecraft:invisibility
  -
    ==: org.bukkit.inventory.ItemStack
    v: 2567
    type: LINGERING_POTION
    meta:
      ==: ItemMeta
      meta-type: POTION
      potion-type: minecraft:long_invisibility