[versions]
pluginYmlPaper = "0.9.0"
paperApi = "1.21.11-R0.1-SNAPSHOT"
customItems = "1.0-SNAPSHOT"
creativeItemFilter = "3.0-SNAPSHOT"

[libraries]
paperApi = { group = "io.papermc.paper", name = "paper-api", version.ref = "paperApi" }
customItems =  { group = "uk.co.notnull", name = "CustomItemsAPI", version.ref  = "customItems" }
creativeItemFilter =  { group = "org.hurricanegames", name = "CreativeItemFilter", version.ref  = "creativeItemFilter" }

[plugins]
pluginYmlPaper = { id = "de.eldoria.plugin-yml.paper", version.ref = "pluginYmlPaper" }
